version: '3.3'
services:
  backend:
    image: evgenferrum/blackfox:latest
    restart: always
    ports:
      - '8000:8000'
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.25.3
    restart: always
    ports:
      - '80:80'
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
